// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaoxvdudhlhxlkktoqeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphb3h2ZHVkaGxoeGxra3RvcWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTAzNDEsImV4cCI6MjA1ODYyNjM0MX0.Iy8TH8HOZzTLhWh1jPBwDdFLJj33vD-QY7IiV1WMMDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);